"""Application settings.

This is the ONLY place in the codebase that reads the environment.
Never call `os.environ` / `os.getenv` anywhere else — inject `Settings` instead.
"""

from __future__ import annotations

from enum import StrEnum
from functools import lru_cache
from typing import Literal

from pydantic import Field, PostgresDsn, computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Environment(StrEnum):
    """Deployment environment. Drives cookie flags, docs exposure and logging."""

    LOCAL = "local"
    STAGING = "staging"
    PRODUCTION = "production"


class Settings(BaseSettings):
    """Typed application configuration, loaded from environment / `.env`."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        frozen=True,
    )

    # --- Identity ---
    app_name: str = "Kiro"
    environment: Environment = Environment.LOCAL

    # --- Security ---
    # Generated by setup.sh with `openssl rand -hex 32`. Never ship a default.
    secret_key: str = Field(min_length=32)

    # --- Database ---
    database_url: PostgresDsn

    # --- URLs ---
    # Absolute base URL. Required to build links in emails and sitemap.xml,
    # where there is no incoming request to derive the host from.
    base_url: str = "http://localhost:8000"

    # --- Observability ---
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_production(self) -> bool:
        """True in any deployed environment. Gates secure cookies and hides docs."""
        return self.environment is not Environment.LOCAL


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide settings singleton.

    Cached so that `.env` is parsed once. Call `get_settings.cache_clear()`
    in tests that need to override the environment.
    """
    return Settings()
