"""Application settings.

This is the ONLY place in the codebase that reads the environment.
Never call `os.environ` / `os.getenv` anywhere else — inject `Settings` instead.
"""

from __future__ import annotations

from enum import StrEnum
from functools import lru_cache
from typing import Literal

from pydantic import Field, PostgresDsn, computed_field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Environment(StrEnum):
    """Deployment environment. Drives cookie flags, docs exposure and logging."""

    LOCAL = "local"
    STAGING = "staging"
    PRODUCTION = "production"


class EmailProvider(StrEnum):
    """Transactional email backend. One adapter per value, in `app/emails/`."""

    CONSOLE = "console"
    RESEND = "resend"
    SMTP = "smtp"


class Settings(BaseSettings):
    """Typed application configuration, loaded from environment / `.env`."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        frozen=True,
    )

    # --- Identity ---
    app_name: str = "Kiro"
    environment: Environment = Environment.LOCAL

    # --- Security ---
    # Generated by setup.sh with `openssl rand -hex 32`. Never ship a default.
    secret_key: str = Field(min_length=32)

    # --- Database ---
    database_url: PostgresDsn

    # --- URLs ---
    # Absolute base URL. Required to build links in emails and sitemap.xml,
    # where there is no incoming request to derive the host from.
    base_url: str = "http://localhost:8000"

    # --- Transactional email ---
    # `console` prints to stdout instead of sending. It is the default on
    # purpose: a fresh checkout must never be able to email a real person.
    email_provider: EmailProvider = EmailProvider.CONSOLE
    email_from: str = "no-reply@example.com"
    email_from_name: str = ""

    # Only read when email_provider is RESEND.
    resend_api_key: str = ""

    # Only read when email_provider is SMTP.
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""

    # --- Observability ---
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_production(self) -> bool:
        """True in any deployed environment. Gates secure cookies and hides docs."""
        return self.environment is not Environment.LOCAL

    @computed_field  # type: ignore[prop-decorator]
    @property
    def email_from_header(self) -> str:
        """The `From` value every provider sends: `Name <address>`, or bare address."""
        if self.email_from_name:
            return f"{self.email_from_name} <{self.email_from}>"
        return self.email_from

    @model_validator(mode="after")
    def _check_email_provider_is_usable(self) -> Settings:
        """Refuse to boot with an email provider that cannot send.

        Deliberately at startup rather than at send time: the first email a
        project sends is usually a password reset, and discovering there that
        `RESEND_API_KEY` was never filled in means a user locked out of their
        account. A misconfigured deploy should fail loudly and immediately.
        """
        if self.email_provider is EmailProvider.RESEND and not self.resend_api_key:
            raise ValueError("EMAIL_PROVIDER=resend requires RESEND_API_KEY")
        if self.email_provider is EmailProvider.SMTP and not self.smtp_host:
            raise ValueError("EMAIL_PROVIDER=smtp requires SMTP_HOST")
        return self


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide settings singleton.

    Cached so that `.env` is parsed once. Call `get_settings.cache_clear()`
    in tests that need to override the environment.
    """
    return Settings()
