"""add rate limit hits

Revision ID: 938e4b4522a7
Revises: 6f0430c6c939
Created: 2026-09-03 20:00:08.371298+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "938e4b4522a7"
down_revision: str | None = "6f0430c6c939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_hits")),
    )
    op.create_index(
        "ix_rate_limit_hits_bucket_created_at",
        "rate_limit_hits",
        ["bucket", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change.

    Keep this correct: it is what turns a bad deploy into a two-minute rollback
    instead of a restore from backup.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_hits_bucket_created_at", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
